name: "Test"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to be deleted"
        required: false

jobs:
  graphql-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get deployment branch
        if: always()
        id: branch
        uses: octokit/graphql-action@v2.2.20
        env:
          GITHUB_TOKEN: ${{ secrets.LFFG_TOKEN }}
        with:
          query: >
            query($repo: String!, $branch: String!) {
              repository(owner: "lffg", name: $repo) {
                ref(qualifiedName: $branch) {
                  id
                }
              }
            }
          env:
            repo: ${{ github.event.repository.name }}
            branch: ${{ github.event.inputs.branch }}
      - name: Delete deployment branch
        if: always() && fromJSON(steps.branch.outputs.data).repository.ref.id != null
        uses: octokit/graphql-action@v2.2.20
        env:
          GITHUB_TOKEN: ${{ secrets.LFFG_TOKEN }}
        with:
          query: >
            mutation ($ref: ID) {
              deleteRef(input: { refId: $ref }) {
                clientMutationId
              }
            }
          ref: ${{ fromJSON(steps.branch.outputs.data).repository.ref.id }}
