name: Enable GH Auto-Merge

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
      - ready_for_review
  pull_request_review:
    type: [submitted]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
      - run: echo '${{ toJSON(github.event) }}'
