name: "Test PR Python Workflow"

on: [pull_request]

jobs:
  main:
    name: "Main"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - run: ls -a
      - run: pwd

      - run: |
          python3 .github/workflow-scripts/format-pr-body.py <<EOF
          ${{ github.event.pull_request.body }}
          EOF
