name: "Test PR Python Workflow"

on: [pull_request]

jobs:
  main:
    name: "Main"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          
      - run: git ls-files --exclude-standard --others
      - run: git diff --name-only --diff-filter="d" --no-rename origin/main

      - name: "Yarn Install"
        run: yarn

      - name: "Format PR Body"
        id: fmt
        run: |
          python3 .github/workflow-scripts/format-pr-body.py <<EOF
          ${{ github.event.pull_request.body }}
          EOF

      - run: echo "${{ steps.fmt.outputs.fmt_result }}"
