name: "Test PR Python Workflow"

on: [pull_request]

jobs:
  main:
    name: "Main"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: "Yarn Install"
        run: yarn

      - name: "Format PR Body"
        id: fmt
        run: |
          output=$(python3 .github/workflow-scripts/format-pr-body.py <<EOF
          ${{ github.event.pull_request.body }}
          EOF)
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}" 
          echo "::set-output name=fmt_result::$output"

      - run: |
          echo <<EOF
          ${{ steps.fmt.outputs.fmt_result }}
          EOF
      - run: echo ${{ steps.fmt.outputs.fmt_result }}
