name: "Test Cond JSON GHA -> BASH"

on:
  workflow_dispatch:
    inputs:
      value:
        description: "Value to be used"
        required: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: gen
        run: |
          cond='${{ contains(github.event.inputs.value, 'foo') }}'

          out=''

          [[ $cond = "true" ]] && out='true'

          echo "value=$out" >> "$GITHUB_OUTPUT"

      - name: Show
        run: |
          echo "Raw:"
          echo "->${{ steps.gen.outputs.value }}<-"
          echo ""
          echo "JSON:"
          echo "->${{ toJSON(steps.gen.outputs.value) }}<-"

      - name: Eval
        if: steps.gen.outputs.value
        run: echo "woo!"
